version: '3.4'

services:
  kafdrop:
    container_name: kafka-ui
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    depends_on:
      - redpanda
    env_file:
      - ".env"
    networks:
      - redpanda-network

  redpanda:
    container_name: kafka-broker
    image: docker.vectorized.io/vectorized/redpanda:v21.11.3
    networks:
      - redpanda-network
    volumes:
      - ./tmp/storage/redpanda:/var/lib/redpanda/data
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
      - --default-log-level
      - warn

  pgadmin:
    container_name: db-postgres-ui
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ./tmp/pgadmin:/var/lib/pgadmin
    links:
      - postgres:postgres
    depends_on:
      - postgres
    env_file:
      - ".env"
    networks:
      - db-network

  postgres:
    container_name: db-postgres
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/storage/postgres:/var/lib/postgresql/data
    env_file:
      - ".env"
    networks:
      - db-network

  core31.gateway.api:
    container_name: gateway.api
    image: gateway.api:core3.1
    build:
      context: .
      dockerfile: Core31.Gateway.Api/Dockerfile
    ports:
      - 56789:80
      - 54321:443
    links:
      - redpanda
    depends_on:
      - redpanda
    networks:
      - redpanda-network
    environment:
      - KafkaServers=redpanda
      - KafkaTopics__CreateEmail=email-create-requested

  core31.consumers.create_email:
    container_name: consumers.create_email
    image: consumers.create_email:core3.1
    build:
      context: .
      dockerfile: Consumers/Emails/Core31.Consumers.CreateEmail/Dockerfile
    links:
      - postgres
      - redpanda
    depends_on:
      - postgres
      - redpanda
    networks:
      - db-network
      - redpanda-network
    environment:
      - KafkaServers=redpanda
      - EmailsConsumerGroup=emails
      - KafkaTopic=email-create-requested
      - ConnectionStrings__EmailsMs=Server=postgres;port=5432;user id=emails_ms;password=postgres_password;database=ms_emails_development;pooling=true

networks:
  redpanda-network:
      driver: bridge
  db-network:
      driver: bridge
