version: '3.4'

services:
  core31.gateway.api:
    container_name: gateway.api
    image: gateway.api:core3.1
    build:
      context: .
      dockerfile: Core31.Gateway.Api/Dockerfile
    ports:
      - 56789:80
      - 54321:443

  core31.consumers.createemail:
    container_name: consumers.create_email
    image: consumers.create_email:core3.1
    build:
      context: .
      dockerfile: Consumers/Emails/Core31.Consumers.CreateEmail/Dockerfile

